export const algo = {
  message: "Succesfuly",
  pages: 1,
  nextPage: 2,
  prevPage: 0,
  currentPage: 1,
  data: [
    {
      id: 4,
      img: "hnpdhcnb4fdwk592gcma",
      contactValue: "https://aramis-jaime-portfolio.vercel.app/",
      expire: "2024/4/1",
      deleted: true,
      createdAt: "2024-04-08T03:28:17.233Z",
      updatedAt: "2024-04-08T03:28:19.689Z",
      userId: 1,
      sizeId: 4,
      importanceId: 1,
      contactType: "whatsapp",
      sectionId: 2,
      size: {
        id: 4,
        size: 4,
      },
      importance: {
        id: 1,
        importance: "A",
      },
      section: {
        id: 2,
        name: "Main",
      },
    },
    {
      id: 3,
      img: "hnpdhcnb4fdwk592gcma",
      contactValue: "https://aramis-jaime-portfolio.vercel.app/",
      expire: "2024/4/1",
      deleted: true,
      createdAt: "2024-04-08T03:28:15.234Z",
      updatedAt: "2024-04-08T03:28:19.687Z",
      userId: 1,
      sizeId: 3,
      importanceId: 1,
      contactType: "whatsapp",
      sectionId: 2,
      size: {
        id: 3,
        size: 3,
      },
      importance: {
        id: 1,
        importance: "A",
      },
      section: {
        id: 2,
        name: "Main",
      },
    },
    {
      id: 2,
      img: "hnpdhcnb4fdwk592gcma",
      contactValue: "https://aramis-jaime-portfolio.vercel.app/",
      expire: "2024/4/1",
      deleted: true,
      createdAt: "2024-04-08T03:28:12.291Z",
      updatedAt: "2024-04-08T03:28:19.685Z",
      userId: 1,
      sizeId: 2,
      importanceId: 1,
      contactType: "whatsapp",
      sectionId: 2,
      size: {
        id: 2,
        size: 2,
      },
      importance: {
        id: 1,
        importance: "A",
      },
      section: {
        id: 2,
        name: "Main",
      },
    },
    {
      id: 1,
      img: "hnpdhcnb4fdwk592gcma",
      contactValue: "https://aramis-jaime-portfolio.vercel.app/",
      expire: "2024/4/1",
      deleted: true,
      createdAt: "2024-04-08T03:28:08.527Z",
      updatedAt: "2024-04-08T03:28:19.683Z",
      userId: 1,
      sizeId: 1,
      importanceId: 1,
      contactType: "whatsapp",
      sectionId: 2,
      size: {
        id: 1,
        size: 1,
      },
      importance: {
        id: 1,
        importance: "A",
      },
      section: {
        id: 2,
        name: "Main",
      },
    },
  ],
};
